import { useUser } from "@clerk/nextjs";
import Head from "next/head";

export default function Home() {
  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Melcool Shop</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#248d39] to-[#15162c]">
        <h1 className="my-3 text-5xl">Hello {user?.fullName}!</h1>
      </main>
    </>
  );
}
