import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  const { user, isSignedIn } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#248d39] to-[#15162c]">
        <h1 className="my-3 text-5xl">Hello {user?.fullName}!</h1>
        <Image
          src={user?.imageUrl ?? "/assets/avatar.png"}
          width={100}
          height={100}
          alt="user-profile-image"
          className="my-3 rounded-full"
        />
        <div className=" my-3">
          {!isSignedIn ? (
            <SignInButton>
              <button className="h-30 w-40 rounded-lg bg-orange-400 px-4 py-2 text-black">
                Sign in
              </button>
            </SignInButton>
          ) : (
            <SignOutButton>
              <button className="h-30 w-40 rounded-lg bg-orange-400 px-4 py-2 text-black">
                Sign out
              </button>
            </SignOutButton>
          )}
        </div>
      </main>
    </>
  );
}
