/* eslint-disable @typescript-eslint/no-unsafe-member-access */
import { useUser } from "@clerk/nextjs";
import { type Listing } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import ProductCard from "~/components/ProductCard";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();
  const listing = api.listings.list.useQuery();

  return (
    <>
      <Head>
        <title>Melcool Shop</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container  mx-auto  flex flex-col items-center justify-center">
        {isSignedIn ? (
          <>
            <h1 className="my-4 w-full grid-flow-row text-center text-4xl text-gray-50 sm:col-span-2 md:col-span-3 lg:col-span-4 ">
              Items for sale
            </h1>
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
              {listing?.data?.map((product: Listing) => (
                <ProductCard listing={product} key={product.id} />
              ))}
            </div>
          </>
        ) : (
          <h1 className="text-center text-5xl text-gray-50">
            Welcome, please sign in!
          </h1>
        )}
      </main>
    </>
  );
};

export default Home;
